apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: registry.bastian-somon.fr/score-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
          - secretRef:
              name: score-server-secret
      imagePullSecrets:
        - name: registry-creds