version: "3.9"

services:

  # Service for the database
  online-score-db:
    container_name: online-score-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: online_score
    restart: always
    ports:
      - "5452:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  online-score-mailhog:
    container_name: online-score-mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MH_STORAGE: maildir
    volumes:
      - smtp_data:/maildir

  # Service for pg-admin
  pg_admin:
    container_name: pg-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@online-score.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "${PG_PORT:-16543}:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  smtp_data:
  pgadmin-data: