version: "3.9"

services:
  online-score-db:
    container_name: online-score-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data


  online-score-server:
    container_name: online-score-server
    image: bastiansmn/online-score-server:latest
    environment:
      PORT: ${PORT}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIRECTION_URL: ${REDIRECTION_URL}
    ports:
      - "${PORT}:8080"
    depends_on:
      - online-score-db

  # Service for pg-admin
  pg_admin:
    container_name: pg-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@online-score.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "${PG_PORT:-16543}:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
