version: "3.9"

services:
  online-score-db:
    container_name: online-score-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data


  online-score-api:
    container_name: online-score-api
    image: bastiansmn/online-score-server:latest
    environment:
      PORT: ${PORT}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIRECTION_URL: ${REDIRECTION_URL}
    ports:
      - "${PORT}:8080"
    depends_on:
      - online-score-db

volumes:
  db-data:

networks:
  default:
    external:
      name: apps-network
