name: Score server CD

on:
  push:
    branches:
      - master

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file .

      - name: Login and push to container registry
        run: |
          echo ${{ secrets.REGISTRY_PASS }} | docker login registry.bastian-somon.fr -u ${{ secrets.REGISTRY_USER }} --password-stdin
          docker build -t registry.bastian-somon.fr/score-server:latest .
          docker push registry.bastian-somon.fr/score-server:latest

  deploy-infra:
    needs: [build-server]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trigger deploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: apply -k infra/application

  rollout-infra:
    needs: [deploy-infra]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trigger backend rollout
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        with:
          args: rollout restart deployment spring -n score-server
